[modules]
autoload=yes

; Desabilitar SIP antigo (chan_sip) para evitar conflitos de portas com PJSIP
noload = chan_sip.so
load = res_pjsip.so
load = res_pjsip_session.so
load = res_pjsip_sdp_rtp.so
load = res_http_websocket.so
load = res_srtp.so
load = codec_opus.so
load = codec_alaw.so
load = codec_ulaw.so
load = codec_g722.so
